### PR TITLE
Added the basic Express app code to server.js along with /ping route

### PR DESCRIPTION
**Pull request by PRABHAS-VARMA**

### CODE REVIEW

**Comment by PRABHAS-VARMA** [comment]
@CodiumAI-Agent /review

**Comment by PRABHAS-VARMA** [comment]
@CodiumAI-Agent/review

**Comment by PRABHAS-VARMA** [comment]
@CodiumAI-Agent/review

**Comment by PRABHAS-VARMA** [comment]
@CodiumAI-Agent /review

**Review by th3c0d3br34ker — COMMENTED** [review]
Hey @PRABHAS-VARMA , its not a good idea to commiting the `node_modues` folder. Please consider removing it, thanks.

**Comment by PRABHAS-VARMA** [comment]
Hey jainam,

Thanks for the feedback. I created .gitignore file and made sure that node
modules are ignored.


Best regards
Prabhas Varma
Squad 48

**Comment by th3c0d3br34ker** [comment]
hey @PRABHAS-VARMA, you created the `.gitignore` file after committing the `node_modules `folder. I am asking you to remove it.

since, you have added so many files, it is the reason why codium AI is unable to properly review your code.

image


thanks.

**Pull request merged**
